app:
  version: ${APP_VERSION:1.0}

api:
  security:
    token:
      secret: ${JWT_SECRET:my-secret-key-change-in-production}

server:
  servlet:
    context-path: ${APP_CONTEXTO:/api/v1}
  port: ${PORT:8080}
  compression:
    enabled: true
  error:
    include-message: never
    include-binding-errors: never
    include-stacktrace: never
    include-exception: false

spring:
  application:
    name: ${APP_NOME:saude-indigena}
  
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5433/saude_indigena}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:123}
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  
  jpa:
    generate-ddl: false
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        default_schema: ${DATABASE_SCHEMA:saude}
        format_sql: false
        jdbc:
          time_zone: America/Sao_Paulo
  
  flyway:
    enabled: true
    schemas: ${DATABASE_SCHEMA:saude}
    baseline-on-migrate: true
    validate-on-migrate: true

springdoc:
  info:
    title: Saúde Indígena API
    description: Sistema de Gerenciamento de Vacinação Indígena

logging:
  level:
    root: INFO
    com.saude_indigena: INFO
    org.springframework.web: WARN
    org.hibernate: WARN
  
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"